In [1]:
import pandas as pd

In [2]:
propals = pd.read_csv ("http://www.firstpythonnotebook.org/_static/committees.csv")

In [3]:
propals.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 8 columns):
ocd_prop_id               102 non-null object
calaccess_prop_id         102 non-null int64
ccdc_prop_id              102 non-null int64
prop_name                 102 non-null object
ccdc_committee_id         102 non-null int64
calaccess_committee_id    102 non-null int64
committee_name            102 non-null object
committee_position        102 non-null object
dtypes: int64(4), object(4)
memory usage: 4.8+ KB

In [4]:
contris = pd.read_csv ("http://www.firstpythonnotebook.org/_static/contributions.csv")

In [5]:
contris.head (1)

,calaccess_committee_id,committee_name,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
0,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-09-18,BERGMAN,GRETCHEN,SPRING VALLEY,CA,91978,A NEW PATH,EXECUTIVE DIRECTOR,False,84.0

In [6]:
contris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56379 entries, 0 to 56378
Data columns (total 13 columns):
calaccess_committee_id          56379 non-null int64
committee_name                  56379 non-null object
calaccess_filing_id             56379 non-null int64
date_received                   56379 non-null object
contributor_lastname            56375 non-null object
contributor_firstname           53411 non-null object
contributor_city                56369 non-null object
contributor_state               56363 non-null object
contributor_zip                 56366 non-null object
contributor_employer            48572 non-null object
contributor_occupation          53273 non-null object
contributor_is_self_employed    56379 non-null bool
amount                          56379 non-null float64
dtypes: bool(1), float64(1), int64(2), object(9)
memory usage: 3.3+ MB

In [7]:
propals.prop_name.value_counts().reset_index()

                                                index  prop_name
0   PROPOSITION 057 - CRIMINAL SENTENCES. JUVENILE...         13
1   PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTH...         12
2   PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...         11
3   PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...          9
4   PROPOSITION 055 - TAX EXTENSION TO FUND EDUCAT...          8
5   PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...          7
6   PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...          7
7   PROPOSITION 059- SB 254 (CHAPTER 20, STATUTES ...          6
8   PROPOSITION 053 - REVENUE BONDS. STATEWIDE VOT...          4
9   PROPOSITION 054 - LEGISLATURE. LEGISLATION AND...          4
10  PROPOSITION 058 - SB 1174 (CHAPTER 753, STATUT...          4
11  PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...          4
12  PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...          4
13  PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...          3
14  PROPOSITION 061- STATE PRESCRIPTION DRUG PURCH...          3
15  PROPOSITION 060- ADULT FILMS. CONDOMS. HEALTH ...          2
16  PROPOSITION 065- CARRY-OUT BAGS. CHARGES. INIT...          1

In [8]:
propals.prop_name

0      PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...
1      PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...
2      PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...
3      PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...
4      PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...
5      PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...
6      PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...
7      PROPOSITION 053 - REVENUE BONDS. STATEWIDE VOT...
8      PROPOSITION 053 - REVENUE BONDS. STATEWIDE VOT...
9      PROPOSITION 053 - REVENUE BONDS. STATEWIDE VOT...
10     PROPOSITION 053 - REVENUE BONDS. STATEWIDE VOT...
11     PROPOSITION 054 - LEGISLATURE. LEGISLATION AND...
12     PROPOSITION 054 - LEGISLATURE. LEGISLATION AND...
13     PROPOSITION 054 - LEGISLATURE. LEGISLATION AND...
14     PROPOSITION 054 - LEGISLATURE. LEGISLATION AND...
15     PROPOSITION 055 - TAX EXTENSION TO FUND EDUCAT...
16     PROPOSITION 055 - TAX EXTENSION TO FUND EDUCAT...
17     PROPOSITION 055 - TAX EXTENSION TO FUND EDUCAT...
18     PROPOSITION 055 - TAX EXTENSION TO FUND EDUCAT...
19     PROPOSITION 055 - TAX EXTENSION TO FUND EDUCAT...
20     PROPOSITION 055 - TAX EXTENSION TO FUND EDUCAT...
21     PROPOSITION 055 - TAX EXTENSION TO FUND EDUCAT...
22     PROPOSITION 055 - TAX EXTENSION TO FUND EDUCAT...
23     PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTH...
24     PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTH...
25     PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTH...
26     PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTH...
27     PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTH...
28     PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTH...
29     PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTH...
                             ...
72     PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...
73     PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...
74     PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...
75     PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...
76     PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...
77     PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...
78     PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...
79     PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...
80     PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...
81     PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...
82     PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...
83     PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...
84     PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...
85     PROPOSITION 065- CARRY-OUT BAGS. CHARGES. INIT...
86     PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...
87     PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...
88     PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...
89     PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...
90     PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...
91     PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...
92     PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...
93     PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...
94     PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...
95     PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...
96     PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...
97     PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...
98     PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...
99     PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...
100    PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...
101    PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...
Name: prop_name, Length: 102, dtype: object

In [9]:
prop = propals [propals.prop_name == 'PROPOSITION 064- MARIJUANA LEGALIZATION. INITIATIVE STATUTE.']

In [10]:
prop.head(2)

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name,committee_position
74,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT
75,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,457,1382525,NEW APPROACH PAC (MPO),SUPPORT

In [11]:
prop.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11 entries, 74 to 84
Data columns (total 8 columns):
ocd_prop_id               11 non-null object
calaccess_prop_id         11 non-null int64
ccdc_prop_id              11 non-null int64
prop_name                 11 non-null object
ccdc_committee_id         11 non-null int64
calaccess_committee_id    11 non-null int64
committee_name            11 non-null object
committee_position        11 non-null object
dtypes: int64(4), object(4)
memory usage: 616.0+ bytes

In [12]:
merged = pd.merge(prop, contris, on="calaccess_committee_id")

In [13]:
merged.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
0,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-02-04,BRADEN QUIGLEY,LAURA,SACRAMENTO,CA,95825,LBQ STRATEGIES,CONSULTANT,False,100.0
1,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-01-05,"CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...",NaN,IRVINE,CA,92618,NaN,NaN,False,250000.0
2,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-01-29,"CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...",NaN,IRVINE,CA,92618,NaN,NaN,False,250000.0
3,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-03-28,"CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...",NaN,IRVINE,CA,92618,NaN,NaN,False,250000.0
4,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-01-05,DRUG POLICY ACTION,NaN,NEW YORK,NY,10001,NaN,NaN,False,250000.0

In [14]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 860 entries, 0 to 859
Data columns (total 20 columns):
ocd_prop_id                     860 non-null object
calaccess_prop_id               860 non-null int64
ccdc_prop_id                    860 non-null int64
prop_name                       860 non-null object
ccdc_committee_id               860 non-null int64
calaccess_committee_id          860 non-null int64
committee_name_x                860 non-null object
committee_position              860 non-null object
committee_name_y                860 non-null object
calaccess_filing_id             860 non-null int64
date_received                   860 non-null object
contributor_lastname            860 non-null object
contributor_firstname           750 non-null object
contributor_city                860 non-null object
contributor_state               860 non-null object
contributor_zip                 860 non-null object
contributor_employer            657 non-null object
contributor_occupation          742 non-null object
contributor_is_self_employed    860 non-null bool
amount                          860 non-null float64
dtypes: bool(1), float64(1), int64(5), object(13)
memory usage: 91.5+ KB

In [15]:
merged.amount

0          100.00
1       250000.00
2       250000.00
3       250000.00
4       250000.00
5       250000.00
6          100.00
7          100.00
8          100.00
9       250000.00
10      250000.00
11      250000.00
12      250000.00
13      250000.00
14        1000.00
15         100.00
16         100.00
17         100.00
18          25.00
19         100.00
20         100.00
21         100.00
22         100.00
23         100.00
24      250000.00
25         100.00
26         100.00
27         100.00
28          20.00
29        1000.00
          ...
830       1000.00
831        250.00
832        250.00
833        800.00
834        400.00
835      14000.00
836      35000.00
837     120000.00
838      45000.00
839    1000000.00
840     150000.00
841     250000.00
842     250000.00
843     550000.00
844     420000.00
845    1000000.00
846    1970000.00
847      30000.00
848     550000.00
849     420000.00
850    1000000.00
851    1970000.00
852    1403000.00
853     500000.00
854     200000.00
855      97000.00
856       4185.00
857        817.00
858        408.64
859        871.00
Name: amount, Length: 860, dtype: float64

In [16]:
merged.amount.sum()

35177017.640000001

In [17]:
merged.committee_position.value_counts()

SUPPORT    762
OPPOSE      98
Name: committee_position, dtype: int64

In [18]:
support = merged[merged.committee_position == "SUPPORT"]

In [19]:
oppose = merged[merged.committee_position == "OPPOSE"]

In [20]:
support.amount.sum()

32675806.0

In [21]:
oppose.amount.sum()

2501211.6400000001

In [22]:
support.amount.sum() / merged.amount.sum()

0.92889642704798669

In [23]:
merged.contributor_employer.value_counts()

NONE                                       94
RETIRED                                    10
LOS ANGELES DEPARTMENT OF WATER & POWER     7
APPLE, INC.                                 6
STATE OF CALIFORNIA                         6
SELF                                        5
MICROSOFT                                   5
NETZER & MALMO                              5
BOSTON SCIENTIFIC                           5
JULIE JOLLEY                                5
SOUTHERN CALIFORNIA EDISON                  5
SQUARECHICKEN MEDIA                         4
DESIGN OCTAVES, INC.                        4
USA TRUCK                                   4
MOTOROLA                                    4
FLOW KANA                                   3
MCELFRESH LAW                               3
DAN VIETS ATTORNEY AT LAW                   3
JOHN DUREE                                  3
KHURSID KHOJA                               3
TERRA VISTA MANAGEMENT INC.                 3
THE SEASTEADING INSTITUTE                   3
REQUESTED                                   3
LONZA BIOSCIENCE                            3
OLD HOME POTTERY                            3
DION MARKGRAAFF, CONSULTANT                 3
TORTUGA ADVISERS LLC                        3
PHYSICAL OPTICS CORPORATION                 3
TEKSYSTEMS                                  3
CM COLLINS ASSOCIATION, INC.                3
                                           ..
HITTER FAMILY FOUNDATION                    1
W VAPES                                     1
LIZADA CAPITAL                              1
METROPOLITAN WELLNESS CENTER                1
DAVID REAGAN                                1
LIEFF CABRASER HEIMANN & BERNSTEIN          1
CZA, INC.                                   1
STRIAR DEVELOPMENT                          1
ONTARIO BASE HOSPITAL GROUP                 1
JARROTT & CO. REAL ESTATE INVESTMENTS       1
DIAMOND EQUITY PARTNERS                     1
BAY AREA BICYCLE LAW                        1
CHRISTOPHER IOVENKO                         1
PERSKY FINANCIAL MANAGEMENT                 1
RECURRENT ENERGY                            1
THE NATURE CONSERVANCY                      1
TRADIV                                      1
CALIFORNIA STATE UNIVERSITY, NORTHRIDGE     1
DEB PETERSEN                                1
JEANNE SULLIVAN                             1
MARIJUANA POLICY GROUP                      1
NOKIA                                       1
IMVU                                        1
INTERFORM                                   1
HANNA P. UTT                                1
CSU FULLERTON                               1
CITY OF ARCADIA                             1
VOLUNTEERMATCH                              1
HOWARD PROPERTIES                           1
RIVERSIDE COUNTY                            1
Name: contributor_employer, Length: 417, dtype: int64

In [24]:
merged.sort_values("amount", ascending=False).head(5)

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
142,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2083528,2016-09-15,PARKER AND AFFILIATED ENTITIES,SEAN,PALO ALTO,CA,94301,NaN,NaN,False,4000000.0
79,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2083528,2016-09-15,"DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...",NaN,SACRAMENTO,CA,95815,NaN,NaN,False,2000000.0
846,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,464,1385506,"DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...",SUPPORT,"DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...",2083608,2016-09-15,FUND FOR POLICY REFORM (NONPROFIT 501 (C)(4)),NaN,NEW YORK,NY,10019,NaN,NaN,False,1970000.0
851,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,465,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),2082414,2016-09-15,FUND FOR POLICY REFORM,NaN,WILMINGTON,DE,19809,NaN,NaN,False,1970000.0
852,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,465,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),2096507,2016-09-27,FUND FOR POLICY REFORM,NaN,WILMINGTON,DE,19809,NaN,NaN,False,1403000.0

In [25]:
merged.groupby("committee_name_x").amount.sum().reset_index().sort_values("amount",ascending=False)

                                     committee_name_x       amount
10  YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...  15734047.00
4        FUND FOR POLICY REFORM (NONPROFIT 501(C)(4))   6140000.00
3   DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...   4470000.00
7                              NEW APPROACH PAC (MPO)   3865000.00
9   SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...   1364000.00
8   PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...   1130930.00
1   CALIFORNIANS FOR RESPONSIBLE MARIJUANA REFORM,...    860470.00
2   CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...    850000.00
5   MARIJUANA POLICY PROJECT OF CALIFORNIA, YES ON 64    739200.00
0          ADULT USE CAMPAIGN FOR PROPOSITION 64; THE     17089.00
6                         MOMS STRONG AGAINST PROP 64      6281.64

In [28]:
merged.groupby(["contributor_firstname", "contributor_lastname"]).amount.sum().reset_index().sort_values("amount", ascending=False)

    contributor_firstname            contributor_lastname     amount
483                  SEAN  PARKER AND AFFILIATED ENTITIES  7250000.0
482                  SEAN                          PARKER  1500000.0
281                 JULIE                         SCHAUER  1364000.0
108                DANIEL                           LEWIS  1250000.0
194                 HENRY                   VAN AMERINGEN  1000000.0
405              NICHOLAS                        PRITZKER   900000.0
421                 PETER                           THIEL   300000.0
456                 ROGER                         JENKINS    75000.0
23                 ANGELA                          HOWARD    65000.0
322              LAWRENCE                            HESS    30000.0
221                 JASON                            POST    10000.0
460              ROGER B.                         MCNAMEE    10000.0
548           ZACHARY PYM                        WILLIAMS    10000.0
239                JEREMY                         ZACHARY     7500.0
440                ROBERT                           ADAMS     6500.0
320                LAURIE                        BENENSON     5000.0
63                CAMILLA                           FIELD     5000.0
375               MICHAEL                            DEAN     5000.0
361            MARY QUINN                         DELANEY     5000.0
488             SHARON K.                        CHRISTIE     5000.0
515                 TERRY                          TURNER     3664.0
301              KHURSHID                           KHOJA     3300.0
277                  JULI                        CROCKETT     3000.0
149                  DOUG                        LANPHERE     2920.0
76                CHARLES                           ROVEN     2500.0
158                 EMILY                          PAXHIA     2500.0
414               PATRICK                       MCMANAMON     2500.0
507                STEVEN                          PERSKY     2500.0
382               MICHAEL                       STEINMETZ     2500.0
377               MICHAEL                           KLEIN     2500.0
..                    ...                             ...        ...
75                CHARLES                            LOVE      100.0
191              GRETCHEN                         BERGMAN       84.0
387              MICHELLE                           WOLFF       84.0
385              MICHELLE                          SEXTON       84.0
189                  GREG                           SMITH       75.0
389                  MIKE                         BARNETT       50.0
534                 WENDY                          COLTON       50.0
168                 ETHAN                         BROOKES       50.0
85           CHRISTINE A.                          PORTER       50.0
459                 ROGER                           TOWER       50.0
492                  SKIP                          ROACHE       50.0
335              LJUBOMIR                       BUTUROVIC       50.0
418                 PETER                          KIRSCH       50.0
326               LEONARD                        KAUFMANN       50.0
104                  DANA                          HIRSCH       50.0
105                DANIEL                          DODSON       50.0
125                 DAVID                          MURRAY       50.0
272                  JOSH                       KLEYMEYER       42.0
51                  BRIAN                        MITCHELL       35.0
533                 WAYNE                         SCHERER       30.0
448                ROBERT                         LOCKART       25.0
185                GEORGE                          OKEEFE       25.0
510               SUE ANN                           LORIG       25.0
355                  MARK                        SLABAUGH       25.0
540               WILLIAM                        SANTSCHI       25.0
430                  RICH                        GOLDBERG       25.0
358               MARSTON                         MEDLOCK        0.0
497             STEPHANIE                 WARREN-SAMARIPA        0.0
16             AMIRGHASEM                 SAMIMI-ARDESTAN        0.0
136                 DAVID                            WOOD        0.0

[549 rows x 3 columns]

In [29]:
merged.groupby(["contributor_firstname", "contributor_lastname", ""]).amount.sum().reset_index().sort_values("amount", ascending=False)

,contributor_firstname,contributor_lastname,committee_position,amount
483,SEAN,PARKER AND AFFILIATED ENTITIES,SUPPORT,7250000.0
482,SEAN,PARKER,SUPPORT,1500000.0
281,JULIE,SCHAUER,OPPOSE,1364000.0
108,DANIEL,LEWIS,SUPPORT,1250000.0
194,HENRY,VAN AMERINGEN,SUPPORT,1000000.0
405,NICHOLAS,PRITZKER,SUPPORT,900000.0
421,PETER,THIEL,SUPPORT,300000.0
456,ROGER,JENKINS,SUPPORT,75000.0
23,ANGELA,HOWARD,SUPPORT,65000.0
322,LAWRENCE,HESS,SUPPORT,30000.0
221,JASON,POST,SUPPORT,10000.0
460,ROGER B.,MCNAMEE,SUPPORT,10000.0
548,ZACHARY PYM,WILLIAMS,SUPPORT,10000.0
239,JEREMY,ZACHARY,SUPPORT,7500.0
440,ROBERT,ADAMS,OPPOSE,6500.0
320,LAURIE,BENENSON,SUPPORT,5000.0
63,CAMILLA,FIELD,SUPPORT,5000.0
375,MICHAEL,DEAN,OPPOSE,5000.0
361,MARY QUINN,DELANEY,SUPPORT,5000.0
488,SHARON K.,CHRISTIE,SUPPORT,5000.0
515,TERRY,TURNER,SUPPORT,3664.0
301,KHURSHID,KHOJA,SUPPORT,3300.0
277,JULI,CROCKETT,SUPPORT,3000.0
149,DOUG,LANPHERE,SUPPORT,2920.0
76,CHARLES,ROVEN,SUPPORT,2500.0
158,EMILY,PAXHIA,SUPPORT,2500.0
414,PATRICK,MCMANAMON,SUPPORT,2500.0
507,STEVEN,PERSKY,SUPPORT,2500.0
382,MICHAEL,STEINMETZ,SUPPORT,2500.0
377,MICHAEL,KLEIN,SUPPORT,2500.0
...,...,...,...,...
75,CHARLES,LOVE,SUPPORT,100.0
191,GRETCHEN,BERGMAN,SUPPORT,84.0
387,MICHELLE,WOLFF,SUPPORT,84.0
385,MICHELLE,SEXTON,SUPPORT,84.0
189,GREG,SMITH,SUPPORT,75.0
389,MIKE,BARNETT,SUPPORT,50.0
534,WENDY,COLTON,SUPPORT,50.0
168,ETHAN,BROOKES,SUPPORT,50.0
85,CHRISTINE A.,PORTER,SUPPORT,50.0
459,ROGER,TOWER,SUPPORT,50.0
492,SKIP,ROACHE,SUPPORT,50.0
335,LJUBOMIR,BUTUROVIC,SUPPORT,50.0
418,PETER,KIRSCH,SUPPORT,50.0
326,LEONARD,KAUFMANN,SUPPORT,50.0
104,DANA,HIRSCH,SUPPORT,50.0
105,DANIEL,DODSON,SUPPORT,50.0
125,DAVID,MURRAY,SUPPORT,50.0
272,JOSH,KLEYMEYER,SUPPORT,42.0
51,BRIAN,MITCHELL,SUPPORT,35.0
533,WAYNE,SCHERER,SUPPORT,30.0
448,ROBERT,LOCKART,SUPPORT,25.0
185,GEORGE,OKEEFE,SUPPORT,25.0
510,SUE ANN,LORIG,SUPPORT,25.0
355,MARK,SLABAUGH,SUPPORT,25.0
540,WILLIAM,SANTSCHI,SUPPORT,25.0
430,RICH,GOLDBERG,SUPPORT,25.0
358,MARSTON,MEDLOCK,SUPPORT,0.0
497,STEPHANIE,WARREN-SAMARIPA,SUPPORT,0.0
16,AMIRGHASEM,SAMIMI-ARDESTAN,SUPPORT,0.0
136,DAVID,WOOD,SUPPORT,0.0

In [33]:
merged.groupby(["contributor_employer", "committee_position"]).amount.sum().reset_index().sort_values("amount", ascending=False)

,contributor_employer,committee_position,amount
349,SEAN PARKER FOUNDATION,SUPPORT,1250000.0
320,RETIRED,SUPPORT,502300.0
381,TAO CAPITAL PARTNERS LLC,SUPPORT,450000.0
382,"TAO CAPITAL PARTNERS, LLC",SUPPORT,450000.0
392,"THIEL CAPITAL, LLC",SUPPORT,300000.0
348,SEAN N PARKER FOUNDATION,SUPPORT,250000.0
292,NONE,SUPPORT,86927.0
134,DESIGNER,SUPPORT,65000.0
237,"LEHBROS LIMITED, LLC",SUPPORT,30000.0
310,POST INVESTMENT GROUP,SUPPORT,10000.0
152,ELEVATION PARTNERS,SUPPORT,10000.0
111,CONDE NAST TRAVELER,SUPPORT,10000.0
117,CS,OPPOSE,6500.0
121,CULTURE MAGAZINE,SUPPORT,5000.0
14,AKONADI FOUNDATION,SUPPORT,5000.0
77,CAMILLA FIELD,SUPPORT,5000.0
36,AROMAFLORIA,SUPPORT,5000.0
233,LAURIE BENENSON,SUPPORT,5000.0
119,CSI,OPPOSE,5000.0
163,FLOW KANA,SUPPORT,3850.0
223,KHURSID KHOJA,SUPPORT,3300.0
412,W VAPES,SUPPORT,3000.0
309,POSEIDON ASSET MANAGEMENT,SUPPORT,2750.0
57,"BIO365, LLC",SUPPORT,2500.0
177,GREEN OREGON ENTERPRISE,SUPPORT,2500.0
80,"CANNASURE INSURANCE SERVICES, LLC",SUPPORT,2500.0
186,HITTER FAMILY FOUNDATION,SUPPORT,2500.0
305,PERSKY FINANCIAL MANAGEMENT,SUPPORT,2500.0
389,THE NARRATIVE METHOD,SUPPORT,2500.0
91,CHARLES ROVEN,SUPPORT,2500.0
...,...,...,...
194,INYO COUNTY,SUPPORT,100.0
198,JAMES SHEPHERD,SUPPORT,100.0
200,JARROTT & CO. REAL ESTATE INVESTMENTS,SUPPORT,100.0
1,3C - COMPREHENSIVE CANNABIS CONSULTING,SUPPORT,100.0
207,JESSICA MCELFRESH,SUPPORT,100.0
205,JEFF WIEDMANN,SUPPORT,100.0
204,JEFF BERKE,SUPPORT,100.0
420,YEN INTERACTIVE MEDIA,SUPPORT,100.0
89,CENTER FOR THE STUDY OF CANNABIS AND SOCIAL PO...,SUPPORT,84.0
270,MICHELLE WOLFF,SUPPORT,84.0
6,A NEW PATH,SUPPORT,84.0
180,GREG SMITH,SUPPORT,75.0
105,CLINICAL PERSONA INC.,SUPPORT,50.0
379,SUSAN PODOLSKY,SUPPORT,50.0
326,"RIVERINE, INC.",SUPPORT,50.0
414,WENDY COLTON,SUPPORT,50.0
125,DANA HIRSCH,SUPPORT,50.0
234,LAW OFFICES OF DAVID REAGAN,SUPPORT,50.0
243,LONZA BIOSCIENCE,SUPPORT,50.0
126,"DANIEL DODSON, INTERNET CONSULTANT",SUPPORT,50.0
108,COASTAL PIPCO,SUPPORT,50.0
358,SKIP ROACHE,SUPPORT,50.0
212,JOSH KLEYMEYER,SUPPORT,42.0
141,DIRECTV,SUPPORT,35.0
413,WAYNE SCHERER,SUPPORT,30.0
74,"CALIFORNIA STATE UNIVERSITY, NORTHRIDGE",SUPPORT,25.0
298,ORBIT TOOL WORKS,SUPPORT,25.0
266,MEDIGREEN,SUPPORT,0.0
61,BORDEN LADNER GERVAIS,SUPPORT,0.0
368,STEPHANIE WARREN SAMARIPA,SUPPORT,0.0